[versions]

# plugins
shadow = "9.3.0"

# compile time processing
lombok = "1.18.42"

# general
guice = "7.0.0"
configura = "dev-b1bb54d"
cloudnet = "4.0.0-RC15"

# testing
junit = "6.0.1"
mockito = "5.21.0"

[libraries]

# compile time processing
lombok = { group = "org.projectlombok", name = "lombok", version.ref = "lombok" }

# general
guice = { group = "com.google.inject", name = "guice", version.ref = "guice" }
configura = { group = "me.whereareiam", name = "configura", version.ref = "configura" }

# cloudnet
cloudnet-node = { group = "eu.cloudnetservice.cloudnet", name = "node-api", version.ref = "cloudnet" }
cloudnet-driver = { group = "eu.cloudnetservice.cloudnet", name = "driver-api", version.ref = "cloudnet" }

# testing
junit-jupiter = { group = "org.junit.jupiter", name = "junit-jupiter", version.ref = "junit" }
junit-platform = { group = "org.junit.platform", name = "junit-platform-launcher" }
mockito-core = { group = "org.mockito", name = "mockito-core", version.ref = "mockito" }
mockito-junit = { group = "org.mockito", name = "mockito-junit-jupiter", version.ref = "mockito" }

[bundles]

testing = ["junit-jupiter", "mockito-core", "mockito-junit"]

[plugins]

shadow = { id = "com.gradleup.shadow", version.ref = "shadow" }


